### ISSUE TITLE
gene page: useless annoying error if alphafold section is opened

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/ApiCommonWebsite#147]
https://redmine.apidb.org/issues/51203

<img width="1188" alt="Screen Shot 2023-04-06 at 12 42 03 PM" src="https://user-images.githubusercontent.com/16354313/230468620-7d443a7c-079b-4422-b535-c5009f816fcf.png">
<img width="900" alt="Screen Shot 2023-04-06 at 2 52 41 PM" src="https://user-images.githubusercontent.com/16354313/230469221-406c9ddd-cff9-40a8-b600-51012a4343fd.png">

to reproduce:
1- go to a gene page with the alphafold section (run a search to get a a gene:
 https://plasmodb.org/plasmo/app/search/transcript/GenesWithAlphafold)
2- in the gene page open the alphafold viz section.
3- go to any other gene page (doesnt matter if it has the section or not), and you get the error.

I think we should either:
1- not save the section open ever (currently added to the local storage as an array of sections: 
@@ebrc@@/expandedSections/GeneRecordClasses.GeneRecordClass)
OR
2- do not throw the error

2 is better because other actions might trigger it too?

**Comment by jernestmyers** [comment]
Worth noting that [this issue was reported and fixed](https://github.com/molstar/molstar/pull/569/files) in `molstar`. The fix was then included [in release `3.19.0`](https://github.com/molstar/molstar/releases/tag/v3.19.0).

We are using `pdbe-molstar`, which hasn't been updated since Oct 24, 2022 and i[t uses `molstar` v3.15.0](https://github.com/molstar/pdbe-molstar/blob/master/package.json#L76). We should consider using `molstar` directly since it seems to be regularly maintained.
